---
- include_vars: "{{ item }}"
  with_first_found:
   - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
   - "../vars/{{ansible_distribution }}.yml"
   - "../vars/{{ ansible_os_family }}.yml"
   - "../vars/default.yml"
  when: apache_package_name is not defined or apache_service_name is not defined

- name: Install Apache HTTPd 
  package: state=latest name="{{ apache_httpd_package_name }}" 

- name: Ensure httpd is running and enabled
  service: name=httpd state=started enabled=yes

- name: Open up 443 and 80 in firewalld
  firewalld: service=http permanent=true state=enabled
  when:
    (ansible_os_family == "RedHat") and
    (ansible_distribution_major_version == "7")

- name: Setup virtual hosts
  notify: restart httpd
  template: 
    src=virtualhost.j2
    dest=/etc/httpd/conf.d/{{item.name}}.conf
    owner=root
    group=root
  with_items:
    - "{{ virtual_hosts }}"

 
